config/routes.rb
SimonDeCirene::Application.routes.draw do
  resources :mensaje_usuarios


  resources :mensajes

  match "/mensajes/:id/delete", to: "mensajes#delete", :as => :delete_mensaje, :via => :get

  match "/not_authorized", to: "home#not_authorized", :as => :not_authorized, :via => :get

  match "/mensajes/new/:id", to: "mensajes#new_with_receiver", :as => :new_mensaje_with_receiver, :via => :get

  resources :formulario_cursos


  resources :formularios do
    collection do
      post :asignar
    end
  end

  match "/formulario/:id/delete", to: "formularios#delete", :as => :delete_formulario, :via => :get
  match "/formulario/:id/asign", to: "formularios#asign", :as => :asign_formulario, :via => :get
  match "/formulario/:id/repeat", to: "formularios#repeat", :as => :repeat_formulario, :via => :get
  match "/formulario/:id/repeat", to: "formularios#repetir", :as => :repetir_formulario, :via => :post
  match "/formulario/resumen", to: "formularios#resumen", :as => :resumen_formularios, :via => :get
  match "/formulario/:id/resumen", to: "formularios#resumen_formulario", :as => :resumen_formulario, :via => :get

  resources :programas

  match "/programas/:id/delete", to: "programas#delete", :as => :delete_programa, :via => :get
  match "/programas/:id/set_active", to: "programas#set_active", :as => :programa_set_active, :via => :post
  match "/programas_inactivos", to: "programas#index_inactivos", :as => :programas_inactivos, :via => :get
  match "/programas_inactivos/:id", to: "programas#show_inactivos", :as => :programa_inactivo, :via => :get


  resources :alumnos do
    collection do
      post :import
      post :search
    end
  end

  match "/cursos/:curso_id/delete_all_alumnos", to: "alumnos#delete_all", :as => :delete_all_alumnos, :via => :get
  match "/cursos/:curso_id/destroy_all_alumnos", to: "alumnos#destroy_all", :as => :destroy_all_alumnos, :via => :get

  match "/cursos/:curso_id/delete_alumno/:id", to: "alumnos#delete", :as => :delete_alumno, :via => :get
  match "/cursos/:id/new_alumno", to: "alumnos#new", :as => :new_alumno, :via => :get
  match "/cursos/:curso_id/edit_alumno/:id", to: "alumnos#edit", :as => :edit_alumno, :via => :get


  resources :sesions

  match "/sesion/:id/delete", to: "sesions#delete", :as => :delete_sesion, :via => :get
  match "/sesion/:id/borrar_asistencia", to: "sesions#borrar_asistencia", :as => :sesion_borrar_asistencia, :via => :post
  match "/cursos/:id/new_sesion", to: "sesions#new", :as => :new_sesion, :via => :get


  resources :cursos, :controller => "cursos"

  match "/cursos/:id/delete", to: "cursos#delete", :as => :delete_curso, :via => :get
  match "/cursos/:id/asistencia", to: "sesions#asistencia", :as => :asistencia_curso, :via => :get
  match "/curso/resumen", to: "cursos#resumen", :as => :resumen_cursos, :via => :get
  match "/cursos_inactivos", to: "cursos#index_inactivos", :as => :cursos_inactivos, :via => :get
  match "/cursos_inactivos/:id", to: "cursos#show_inactivos", :as => :curso_inactivo, :via => :get
  match "/curso_inactivo/resumen", to: "cursos#resumen_inactivos", :as => :resumen_cursos_inactivos, :via => :get

  match "/cursos/:id", to: "cursos#update", :as => :update_curso, :via => :put
  match "/sesions/:id/details", to: "sesions#details", :as => :sesion_details, :via => :get
  match "/alumnos/:id/details", to: "alumnos#details", :as => :alumno_details, :via => :get
  match "/sesions/curso/:id", to: "sesions#curso", :as => :sesion_curso, :via => :get
  match "/alumnos/asistencia/:id", to: "alumnos#asistencia", :via => :post
  match "/download/excel_tipo", to: "alumnos#download_excel"
  match "/curso/:curso_id/formulario/:formulario_id", to: "cursos#formulario", :as => :curso_formulario, :via => :get
  match "/curso/:curso_id/formulario/:formulario_id", to: "cursos#formulario_completado", :via => :post
  match "/ayuda/formularios", to: "home#ayuda_formularios", :as => :ayuda_formulario, :via => :get
  match "/cursos/importar_excel_sence", to: "alumnos#import_sence", :as => :import_excel_sence, :via => :post
  match "/resumen/programa/:id", to: "home#resumen_programa", :as => :resumen_programa, :via => :get
  match "/resumen/curso/:id", to: "home#resumen_curso", :as => :resumen_curso, :via => :get

  authenticated :user do
    root :to => 'home#index'
  end

  match "/user/:id/delete", to: "users#delete", :as => :delete_user, :via => :get

  root :to => "home#index"
  match "/calendario", to: "home#calendario", :as => :calendario, :via => :get

  devise_for :users, :skip => [:registrations]
  devise_scope :user do
  	post "user_registration", 		:to => "users#create"
  	get "edit_user_registration",   :to => "users#edit"
  end
  resources :users, :controller => "users"
  resource :user, only: [:edit] do
    collection do
      put 'update_password'
    end
  end
end

app/models/formulario.rb
class Formulario < ActiveRecord::Base
  attr_accessible :codigo, :url, :nombre, :tipo

  validates :codigo, :url, :nombre, :tipo, :presence => true

  def estado(curso)
  	return FormularioCurso.where(:formulario_id => self, :curso_id => curso).first.estado
  end

  def contestado?(curso)
    formulario_curso = FormularioCurso.where(:formulario_id => self, :curso_id => curso).first
    return formulario_curso.contestado?
  end

  def pendientes(curso)
    formulario_curso =  FormularioCurso.where(:formulario_id => self, :curso_id => curso).first
    return formulario_curso.pendientes
  end

  def contestados(curso)
    formulario_curso =  FormularioCurso.where(:formulario_id => self, :curso_id => curso).first
    unless formulario_curso.nil?
      return formulario_curso.contestados
    else
      return 0
    end
  end

  def contestados
    contador = 0
      FormularioCurso.where(:formulario_id => self).all.each do |formulario_curso|
        unless formulario_curso.nil?
          if formulario_curso.contestado?
            contador = contador +  1
          end
        end
      end
    return contador
  end

  def pendientes
    contador = 0
      FormularioCurso.where(:formulario_id => self).all.each do |formulario_curso|
        unless formulario_curso.nil?
          if formulario_curso.pendiente?
            contador = contador +  1
          end
        end
      end
    return contador
  end

  def no_asignados
    cursos = Curso.all.count
    return cursos - self.contestados - self.pendientes
  end

  def cursos_ids
    cursos = Array.new
    curso_ids = FormularioCurso.where(:formulario_id => self).select(:curso_id).group(:curso_id).collect{|p| p.curso_id}
    curso_ids.each do |curso_id|
      cursos.push curso_id
    end
    return cursos
  end

  def cursos
    cursos = Array.new
    curso_ids = FormularioCurso.where(:formulario_id => self).select(:curso_id).group(:curso_id).collect{|p| p.curso_id}
    curso_ids.each do |curso_id|
      cursos.push Curso.find(curso_id)
    end
    return cursos
  end

  def eliminar_cursos
    curso_ids = FormularioCurso.where(:formulario_id => self).select(:curso_id).group(:curso_id).collect{|p| p.curso_id}
    curso_ids.each do |curso_id|
      FormularioCurso.where(:formulario_id => self, :curso_id => curso_id).destroy_all
    end
  end

  def duplicates(curso_id)
    unless FormularioCurso.where(:formulario_id => self, :curso_id => curso_id).first.nil?
      return FormularioCurso.where(:formulario_id => self, :curso_id => curso_id).first.duplicates
    else
      return 1
    end
  end

  def eliminar_curso(curso_id)
    FormularioCurso.where(:formulario_id => self, :curso_id => curso_id).destroy_all
  end
end

app/controllers/formularios_controller.rb
require 'rubygems'
require 'nokogiri'
require 'open-uri'

class FormulariosController < ApplicationController
  # GET /formularios
  # GET /formularios.json
  def index
    @formularios = Formulario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @formularios }
    end
  end

  # GET /formularios/1
  # GET /formularios/1.json
  def show
    @formulario = Formulario.find(params[:id])
    pagina = Nokogiri::HTML(open(@formulario.url))
    @cuerpo = pagina.css('form').to_html

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @formulario }
    end
  end

  # GET /formularios/new
  # GET /formularios/new.json
  def new
    @formulario = Formulario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @formulario }
    end
  end

  # GET /formularios/1/edit
  def edit
    @formulario = Formulario.find(params[:id])
  end

  # POST /formularios
  # POST /formularios.json
  def create
    @formulario = Formulario.new(params[:formulario])

    respond_to do |format|
      if @formulario.save
        format.html { redirect_to formularios_path }
        format.json { render json: @formulario, status: :created, location: @formulario }
      else
        format.html { render action: "new" }
        format.json { render json: @formulario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /formularios/1
  # PUT /formularios/1.json
  def update
    @formulario = Formulario.find(params[:id])

    respond_to do |format|
      if @formulario.update_attributes(params[:formulario])
        format.html { redirect_to formularios_path }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @formulario.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @formulario = Formulario.find(params[:id])
  end

  # DELETE /formularios/1
  # DELETE /formularios/1.json
  def destroy
    @formulario = Formulario.find(params[:id])
    @formulario.destroy

    FormularioCurso.where(:formulario_id => @formulario).destroy_all

    respond_to do |format|
      format.html { redirect_to formularios_url }
      format.json { head :no_content }
    end
  end

  def asign
    @formulario = Formulario.find(params[:id])
  end

  def repeat
    @formulario = Formulario.find(params[:id])
  end

  def asignar
    formulario_id = params[:formulario_id]
    @formulario = Formulario.find(formulario_id)
    duplicates = Hash.new
    contestados = Hash.new
    if !params[:cursos_ids].nil?
      params[:cursos_ids].each do |curso_id|
        duplicates[curso_id] = @formulario.duplicates(curso_id)
        contestados[curso_id] = @formulario.contestados
      end
      Formulario.find(params[:formulario_id]).eliminar_cursos
      params[:cursos_ids].each do |curso_id|
        FormularioCurso.create(:curso_id => curso_id, :formulario_id => formulario_id, :estado => "Pendiente", :duplicates => duplicates[curso_id], :contestados => contestados[curso_id] )
      end
    else
      Formulario.find(params[:formulario_id]).eliminar_cursos
    end
    redirect_to formularios_path
  end

  def repetir
    FormularioCurso.where(:formulario_id => params[:id], :curso_id => params[:curso_id]).first.update_attributes(:duplicates => params[:numero].to_i)
    render :nothing => true
  end

  def resumen
    @formularios = Formulario.all
    @cursos = Curso.all_active

    respond_to do |format|
      format.html # resumen.html.erb
      format.xls do
        response.headers['Content-Disposition'] = 'attachment; filename="Resumen Formularios.xls"'
        render "resumen.xls.erb"
      end
    end
  end

  def resumen_formulario
    @formulario = Formulario.find(params[:id])
    @cursos = Curso.all_active

    respond_to do |format|
      format.xls do
        response.headers['Content-Disposition'] = 'attachment; filename="' + @formulario.nombre + '.xls"'
        render "resumen_formulario.xls.erb"
      end
    end
  end
end

app/helpers/formularios_helper.rb
module FormulariosHelper
end

app/views/formularios/_asign.html.erb
<div>
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3>Asignar Formulario <%= @formulario.nombre %></h3>
    </div>
    <%= form_tag(asignar_formularios_path, :method=>'post') do %>
    <div class="modal-body">
      <%= select_tag 'cursos_ids[]', options_for_select(Curso.all_active.map {|c| [c.relator_codigo, c.id]}), :multiple => true, :class => "input-block-level", :id => "select-formulario" %>
      <label class="checkbox inline">
        <input class="btn" value="Input" type="checkbox" id="checkbox" >Seleccionar Todos
      </label>
      <input type="hidden" id="formulario_id" name="formulario_id" value="<%= @formulario.id %>" />
    </div>
    <script type="text/javascript">
      $("#select-formulario").val(<%= raw @formulario.cursos_ids %>).select2({
        placeholder: "Selecciona uno o varios cursos"
      });
      $("#checkbox").click(function(){
        if($("#checkbox").is(':checked') ){
          $("#select-formulario > option").prop("selected","selected");
          $("#select-formulario").trigger("change");
        }
        else{
          $("#select-formulario > option").removeAttr("selected");
          $("#select-formulario").trigger("change");
        }
      });
    </script>
    <div class="modal-footer">
      <%= submit_tag "Asignar", :class => "btn btn-info" %>
      <% end %>
      <a class="btn" data-dismiss="modal" href="#">Cerrar</a>
    </div>
</div>

app/views/formularios/_delete.html.erb
<div>
  <div class="modal-header">
  	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h2>Eliminar</h2>
  </div>
	<div class="modal-body">
		<p>Estás a punto de eliminar el formulario</p>
		<br />
		<h4 align="center"><%= @formulario.codigo %> <%= @formulario.nombre %></h4>
		<br />
	</div>
	<div class="modal-footer">
		<%= link_to("Eliminar", @formulario, :method => :delete, :class => 'btn btn-inverse') %>
		<a href="#" class="btn" data-dismiss="modal">Cancelar</a>
	</div>
</div>

app/views/formularios/_form.html.erb
<%= simple_form_for(@formulario) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :codigo, :autofocus => true, :label => false, :placeholder => 'Código' %>
    <%= f.input :nombre, :label => false, :placeholder => 'Nombre' %>
    <p>Tipo:</p>
    <%= f.input :tipo, :collection => ['Social', 'Microempresas'], :label => false, :prompt => "" %>
    <p>Pega la url del formulario de Google Drive aqui: <%= link_to('<i class="icon-question-sign"></i>'.html_safe, ayuda_formulario_path, :class => 'btn btn-mini') %></p>
    <%= f.input :url, :label => false, :input_html => { :class => "input-block-level" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Enviar", :class => 'btn-info' %>
    <% end %>
  <%= link_to("Atrás", formularios_path, :class => 'btn') %>
</div>

app/views/formularios/_repeat.html.erb
<div>
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h4>Formulario <%= @formulario.nombre %></h4>
    </div>
    <div class="modal-body">
      <% if @formulario.cursos.any? %>
      <table class="table">
        <% @formulario.cursos.each do |curso| %>
          <tr>
            <td><%= curso.relator_codigo %></td> 
            <td><input name="curso-<%=curso.id%>" id="slider-curso-<%=curso.id%>" type="text" class="slider" data-slider-min="1" data-slider-max="30" data-slider-step="1" data-slider-value="<%= @formulario.duplicates(curso) %>" data-slider-orientation="horizontal" data-slider-selection="after" data-slider-tooltip="hide"></td>
            <td><button id="data-slider-curso-<%=curso.id%>" class="btn btn-mini btn-info disabled"></button></td>
            <script type="text/javascript">
              var slider = $('#slider-curso-<%=curso.id%>').slider();
              slider.on('slide', showSliderValue);
              slider.on('slideStop', sendSliderValue);
              $('#data-slider-curso-<%=curso.id%>').html('<%= @formulario.duplicates(curso) %>');
              function showSliderValue(){
                $('#data-slider-curso-<%=curso.id%>').html($(this).slider('getValue'));
              };
              function sendSliderValue(){
                $.ajax({
                  type: "POST",
                  url: "/formulario/<%= @formulario.id %>/repeat",
                  data: {curso_id: '<%= curso.id %>', numero: $(this).slider('getValue')}
                });
              };
            </script>
          </tr>
        <% end %>
      </table>
      <% else %>
        <p>Este formulario todavía no tiene ningún curso asignado</p>
      <% end %>
    </div>
    <div class="modal-footer">
      <a class="btn btn-info" data-dismiss="modal" href="#">Listo</a>
    </div>
</div>

app/views/formularios/asign.js.erb
$("#formulario-modal").html("<%= escape_javascript(render :partial => 'asign') %>")
$("#formulario-modal").modal("show")

app/views/formularios/delete.js.erb
$("#formulario-modal").html("<%= escape_javascript(render :partial => 'delete') %>")
$("#formulario-modal").modal("show")

app/views/formularios/edit.html.erb
<div class="span2"></div>
<div class="span8">
	<h1>Editar Formulario</h1>
	<br>
	<%= render 'form' %>
</div>

app/views/formularios/index.html.erb
<div class="span2"></div>
<div class="span8">
  <h3>Formularios</h3>
  <% if @formularios.any? %>
    <table class="table table-condensed table-striped sortable">
      <thead>
        <tr>
          <th>Código</th>
          <th>Nombre</th>
          <th>Tipo</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @formularios.each do |formulario| %>
          <tr>
            <td><%= formulario.codigo %></td>
            <td><%= formulario.nombre %></td>
            <td><%= formulario.tipo %></td>
            <td>
              <div class="btn-group">
                <%= link_to('Asignar', asign_formulario_path(formulario), remote: true, class: "btn btn-mini") %>
              </div>
            </td>
            <td>
              <div class="btn-group">
                <%= link_to('<i class="icon-search"></i>'.html_safe, formulario.url, :class => 'btn btn-mini') %>
                <%= link_to('<i class="icon-pencil"></i>'.html_safe, edit_formulario_path(formulario), :class => 'btn btn-mini') %>
                <%= link_to('<i class="icon-trash icon-white"></i>'.html_safe, delete_formulario_path(formulario), remote: true, class: "btn btn-mini btn-inverse") %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <br />
  <% end %>
  <%= link_to("Nuevo Formulario", new_formulario_path, :class => 'btn btn-mini btn-info') %>
  <div id="formulario-modal" class="modal hide fade"></div>
</div>

app/views/formularios/new.html.erb
<div class="span2"></div>
<div class="span8">
	<h1>Nuevo Formulario</h1>
	<br>
	<%= render 'form' %>
</div>

app/views/formularios/repeat.js.erb
$("#formulario-modal").html("<%= escape_javascript(render :partial => 'repeat') %>")
$("#formulario-modal").modal("show")

app/views/formularios/resumen.html.erb
<div class="span1"></div>
<div class="span10" style="overflow: auto">
	<h3>Resumen Formularios</h3>
	<% if @formularios.empty? %>
		<h4>Todavía no existen formularios</h4>
	<% elsif @cursos.empty? %>
		<h4>Todavía no existen cursos</h4>
	<% else %>
		<table class="table table-condensed table-striped">
			<thead>
				<tr>
					<td></td>
					<td></td>
					<% @formularios.each do |formulario| %>
						<td> 
							<div class="btn-group" style="width: 100%;">
								<button class="btn btn-mini btn-success disabled" style="width: 33%;"><%= formulario.contestados %></button>
								<button class="btn btn-mini btn-danger disabled" style="width: 33%;"><%= formulario.pendientes %></button>
								<button class="btn btn-mini btn-warning disabled" style="width: 33%;"><%= formulario.no_asignados %></button>
							</div>
						</td>
					<% end %>
				</tr>
				<tr>
					<th></th>
					<th>Curso</th>
					<% @formularios.each do |formulario| %>
						<th class="centered"><span data-placement="top" class="resumen-tooltip" title="<%= formulario.nombre %>"><%= link_to formulario.codigo, resumen_formulario_path(formulario, format: "xls"), :class => 'btn btn-mini btn-success' %></span></th>
					<% end %>
				</tr>
			</thead>
			<tbody>
				<% @cursos.each do |curso| %>
				<tr>
					<td>
						<div class="btn-group">
							<button class="btn btn-mini btn-success disabled"><%= curso.formularios_contestados %></button>
							<button class="btn btn-mini btn-danger disabled"><%= curso.formularios_pendientes %></button>
							<button class="btn btn-mini btn-warning disabled"><%= curso.formularios_no_asignados %></button>
						</div>
					</td>
					<td><%= link_to(curso.codigo + " - " + curso.nombre, new_mensaje_with_receiver_path(curso.relator_jefe_id), remote: true, :class => 'btn btn-link resumen-tooltip', :title => User.find(curso.relator_jefe_id).name) %></td>
					
					<% @formularios.each do |formulario| %>
						<td class="centered">
							<% if FormularioCurso.where(:formulario_id => formulario, :curso_id => curso).first.nil? %>
								<button type="button" id="contestado-<%= formulario.id %>-<%= curso.id %>" class="btn btn-mini btn-warning disabled">N</button>
							<% elsif formulario.contestado?(curso) %>
								<button type="button" id="contestado-<%= formulario.id %>-<%= curso.id %>" class="btn btn-mini btn-success disabled">C</button>
							<% else %>
								<button type="button" id="contestado-<%= formulario.id %>-<%= curso.id %>" class="btn btn-mini btn-danger disabled">P</button>
							<% end %>
						</td>
						<script type="text/javascript">
		                  $("#contestado-<%= formulario.id %>-<%= curso.id %>").click(function() {
		                    if ($(this).text() == "P") {
		                    	$(this).removeClass("btn-danger");
                    			$(this).addClass("btn-success");
                    			$(this).text("C");
                    			$.ajax({
			                      type: "POST",
			                      url: "/curso/<%= curso.id %>/formulario/<%= formulario.id %>",
			                      data: {estado: 'Contestado'}
			                    });
		                    }
		                    else if ($(this).text() == "C") {
		                    	$(this).removeClass("btn-success");
                    			$(this).addClass("btn-danger");
                    			$(this).text("P");
                    			$.ajax({
			                      type: "POST",
			                      url: "/curso/<%= curso.id %>/formulario/<%= formulario.id %>",
			                      data: {estado: 'Pendiente'}
			                    });
		                    }
		                  });
		                </script>
					<% end %>
				</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>
	<br><br><br>
</div>
<div class="span10">
	<div>
		<div class="span8"><%= render 'layouts/messages' %></div>
		<div class="span4 well well-small">
			<p><button type="button"  class="btn btn-mini btn-success disabled">C</button> Contestado</p>
			<p><button type="button"  class="btn btn-mini btn-warning disabled">N</button> Formulario no asociado a este curso</p>
			<p><button type="button"  class="btn btn-mini btn-danger disabled">P</button> Pendiente</p>
		</div>
	</div>
	<div class="pull-right">
		<%= link_to_function('<i class="icon-print"></i>'.html_safe, "javascript:print()", :class => 'btn btn-mini')%>
		<%= link_to '<i class="icon-download-alt"></i>'.html_safe, resumen_formularios_path(format: "xls"), :class => 'btn btn-mini btn-success' %>
	</div>
</div>

<div id="mensaje-modal" class="modal hide fade modal-mensaje"></div>

app/views/formularios/resumen.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell>Formulario</Cell>
        <% @cursos.each do |curso| %>
          <Cell><Data ss:Type="String"><%= curso.codigo %></Data></Cell>
        <% end %>
      </Row>
      <% @formularios.each do |formulario| %>
        <Row>
          <Cell><Data ss:Type="String"><%= formulario.codigo %></Data></Cell>
          <% @cursos.each do |curso| %>
            <% if FormularioCurso.where(:formulario_id => formulario, :curso_id => curso).first.nil? %>
              <Cell><Data ss:Type="String">N</Data></Cell>
            <% elsif formulario.contestado?(curso) %>
              <Cell><Data ss:Type="String">C</Data></Cell>
            <% else %>
              <Cell><Data ss:Type="String">P</Data></Cell>
            <% end %>
          <% end %>
        </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/formularios/resumen_formulario.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String">Curso</Data></Cell>
        <Cell><Data ss:Type="String">Estado</Data></Cell>
      </Row>
      <% @cursos.each do |curso| %>
        <% if FormularioCurso.where(:formulario_id => @formulario, :curso_id => curso).first.nil? %>
        <% elsif @formulario.contestado?(curso) %>
        <Row>
          <Cell><Data ss:Type="String"></Data></Cell>
          <Cell><Data ss:Type="String"><%= curso.codigo %></Data></Cell>
          <Cell><Data ss:Type="String">Contestado</Data></Cell>
        </Row>
        <% else %>
        <% end %>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/formularios/show.html.erb
<div class="span3"></div>
<div class="span6">
	<h3><%= @formulario.codigo %> <small><%= @formulario.tipo %></small></h3>
	<h4><%= @formulario.nombre %></h4>
	<hr>
	<%= raw @cuerpo %>
	<hr>
	<%= link_to 'Editar', edit_formulario_path(@formulario), :class => "btn btn-info" %>
	<%= link_to 'Atrás', formularios_path, :class => "btn" %>
	<br /><br /><br />
</div>
<script type="text/javascript">
	$("#ss-submit").hide();
</script>