config/routes.rb
SimonDeCirene::Application.routes.draw do
  resources :mensaje_usuarios


  resources :mensajes

  match "/mensajes/:id/delete", to: "mensajes#delete", :as => :delete_mensaje, :via => :get

  match "/not_authorized", to: "home#not_authorized", :as => :not_authorized, :via => :get

  match "/mensajes/new/:id", to: "mensajes#new_with_receiver", :as => :new_mensaje_with_receiver, :via => :get

  resources :formulario_cursos


  resources :formularios do
    collection do
      post :asignar
    end
  end

  match "/formulario/:id/delete", to: "formularios#delete", :as => :delete_formulario, :via => :get
  match "/formulario/:id/asign", to: "formularios#asign", :as => :asign_formulario, :via => :get
  match "/formulario/:id/repeat", to: "formularios#repeat", :as => :repeat_formulario, :via => :get
  match "/formulario/:id/repeat", to: "formularios#repetir", :as => :repetir_formulario, :via => :post
  match "/formulario/resumen", to: "formularios#resumen", :as => :resumen_formularios, :via => :get
  match "/formulario/:id/resumen", to: "formularios#resumen_formulario", :as => :resumen_formulario, :via => :get

  resources :programas

  match "/programas/:id/delete", to: "programas#delete", :as => :delete_programa, :via => :get
  match "/programas/:id/set_active", to: "programas#set_active", :as => :programa_set_active, :via => :post
  match "/programas_inactivos", to: "programas#index_inactivos", :as => :programas_inactivos, :via => :get
  match "/programas_inactivos/:id", to: "programas#show_inactivos", :as => :programa_inactivo, :via => :get


  resources :alumnos do
    collection do
      post :import
      post :search
    end
  end

  match "/cursos/:curso_id/delete_all_alumnos", to: "alumnos#delete_all", :as => :delete_all_alumnos, :via => :get
  match "/cursos/:curso_id/destroy_all_alumnos", to: "alumnos#destroy_all", :as => :destroy_all_alumnos, :via => :get

  match "/cursos/:curso_id/delete_alumno/:id", to: "alumnos#delete", :as => :delete_alumno, :via => :get
  match "/cursos/:id/new_alumno", to: "alumnos#new", :as => :new_alumno, :via => :get
  match "/cursos/:curso_id/edit_alumno/:id", to: "alumnos#edit", :as => :edit_alumno, :via => :get


  resources :sesions

  match "/sesion/:id/delete", to: "sesions#delete", :as => :delete_sesion, :via => :get
  match "/sesion/:id/borrar_asistencia", to: "sesions#borrar_asistencia", :as => :sesion_borrar_asistencia, :via => :post
  match "/cursos/:id/new_sesion", to: "sesions#new", :as => :new_sesion, :via => :get


  resources :cursos, :controller => "cursos"

  match "/cursos/:id/delete", to: "cursos#delete", :as => :delete_curso, :via => :get
  match "/cursos/:id/asistencia", to: "sesions#asistencia", :as => :asistencia_curso, :via => :get
  match "/curso/resumen", to: "cursos#resumen", :as => :resumen_cursos, :via => :get
  match "/cursos_inactivos", to: "cursos#index_inactivos", :as => :cursos_inactivos, :via => :get
  match "/cursos_inactivos/:id", to: "cursos#show_inactivos", :as => :curso_inactivo, :via => :get
  match "/curso_inactivo/resumen", to: "cursos#resumen_inactivos", :as => :resumen_cursos_inactivos, :via => :get

  match "/cursos/:id", to: "cursos#update", :as => :update_curso, :via => :put
  match "/sesions/:id/details", to: "sesions#details", :as => :sesion_details, :via => :get
  match "/alumnos/:id/details", to: "alumnos#details", :as => :alumno_details, :via => :get
  match "/sesions/curso/:id", to: "sesions#curso", :as => :sesion_curso, :via => :get
  match "/alumnos/asistencia/:id", to: "alumnos#asistencia", :via => :post
  match "/download/excel_tipo", to: "alumnos#download_excel"
  match "/curso/:curso_id/formulario/:formulario_id", to: "cursos#formulario", :as => :curso_formulario, :via => :get
  match "/curso/:curso_id/formulario/:formulario_id", to: "cursos#formulario_completado", :via => :post
  match "/ayuda/formularios", to: "home#ayuda_formularios", :as => :ayuda_formulario, :via => :get
  match "/cursos/importar_excel_sence", to: "alumnos#import_sence", :as => :import_excel_sence, :via => :post
  match "/resumen/programa/:id", to: "home#resumen_programa", :as => :resumen_programa, :via => :get
  match "/resumen/curso/:id", to: "home#resumen_curso", :as => :resumen_curso, :via => :get

  authenticated :user do
    root :to => 'home#index'
  end

  match "/user/:id/delete", to: "users#delete", :as => :delete_user, :via => :get

  root :to => "home#index"
  match "/calendario", to: "home#calendario", :as => :calendario, :via => :get

  devise_for :users, :skip => [:registrations]
  devise_scope :user do
  	post "user_registration", 		:to => "users#create"
  	get "edit_user_registration",   :to => "users#edit"
  end
  resources :users, :controller => "users"
  resource :user, only: [:edit] do
    collection do
      put 'update_password'
    end
  end
end

app/models/programa.rb
class Programa < ActiveRecord::Base
	audited
	
	has_many :cursos
	has_many :sesions, :through => :cursos

  	attr_accessible :nombre, :tipo, :active

  	validates :nombre, :tipo, :presence => true
  	validates :tipo, :inclusion => {:in => ["Social", "Microempresas"]}

    def self.all_active
      return Programa.where(:active => true).all
    end

  	def alumnos
  		alumnos = Array.new
  		self.cursos.each do |curso|
  			alumnos_curso = curso.alumnos
  			alumnos_curso.each do |alumno|
  				unless !alumnos_curso.include?(alumno)
  					alumnos.push alumno
  				end
  			end
  		end
  		return alumnos
  	end

  	def sesiones
  		sesiones = Array.new
  		self.cursos.each do |curso|
  			sesiones_curso = curso.sesions
  			sesiones_curso.each do |sesion|
  				unless !sesiones_curso.include?(sesion)
  					sesiones.push sesion
  				end
  			end
  		end
  		return sesiones
  	end

  	def formularios
  		formularios = Array.new
  		self.cursos.each do |curso|
  			formularios_curso = curso.formularios
  			formularios_curso.each do |formulario|
  				unless !formularios_curso.include?(formulario)
  					formularios.push formulario
  				end
  			end
  		end
  		return formularios
  	end

    def asistencia_promedio
      suma = 0
      num_cursos = 0
      self.cursos.each do |curso|
        asistencia = curso.asistencia
        unless asistencia == "NA"
          suma += asistencia
          num_cursos += 1
        end
      end
      if num_cursos != 0 
        return ((suma/num_cursos).round(2)).to_i
      else
        return "NA"
      end
    end

    def asistencia_sobre_el_total_promedio
      suma = 0
      num_cursos = 0
      self.cursos.each do |curso|
        asistencia_sobre_el_total = curso.asistencia_sobre_el_total
        unless asistencia_sobre_el_total == "NA"
          suma += asistencia_sobre_el_total
          num_cursos += 1
        end
      end
      if num_cursos != 0 
        return ((suma/num_cursos).round(2)).to_i
      else
        return "NA"
      end
    end
end

app/controllers/programas_controller.rb
class ProgramasController < ApplicationController
  respond_to :html, :js
  # GET /programas
  # GET /programas.json
  def index
    @programas = Programa.all_active
    @programa = Programa.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programas }
    end
  end

  def index_inactivos
    @programas = Programa.where(:active => false).all
  end

  # GET /programas/1
  # GET /programas/1.json
  def show
    @programa = Programa.find(params[:id])
    @programas_sociales = Programa.where(:tipo => "Social", :active => true).all
    @programas_microempresas = Programa.where(:tipo => "Microempresas", :active => true).all
    @curso = Curso.new
    @cursos = @programa.cursos.where(:active => true).order(:created_at).all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @programa }
      format.xls do
        response.headers['Content-Disposition'] = 'attachment; filename="' + @programa.nombre + '.xls"'
        render "show.xls.erb"
      end
    end
  end

  def show_inactivos
    @programa = Programa.find(params[:id])
    @programas_sociales = Programa.where(:tipo => "Social", :active => false).all
    @programas_microempresas = Programa.where(:tipo => "Microempresas", :active => false).all
    @curso = Curso.new
    @cursos = @programa.cursos.where(:active => false).order(:created_at).all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @programa }
      format.xls do
        response.headers['Content-Disposition'] = 'attachment; filename="' + @programa.nombre + '.xls"'
        render "show.xls.erb"
      end
    end
  end

  # GET /programas/new
  # GET /programas/new.json
  def new
    @programa = Programa.new
  end

  # GET /programas/1/edit
  def edit
    @programa = Programa.find(params[:id])
    session[:return_to] ||= request.referer
  end

  # POST /programas
  # POST /programas.json
  def create
    @programa = Programa.new(params[:programa])

    respond_to do |format|
      if @programa.save
        format.html { redirect_to programas_path }
        format.json { render json: @programa, status: :created, location: @programa }
      else
        format.html { render action: "new" }
        format.json { render json: @programa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programas/1
  # PUT /programas/1.json
  def update
    @programa = Programa.find(params[:id])

    respond_to do |format|
      if @programa.update_attributes(params[:programa])
        format.html { redirect_to session.delete(:return_to) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @programa.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @programa = Programa.find(params[:id])
  end

  # DELETE /programas/1
  # DELETE /programas/1.json
  def destroy
    @programa = Programa.find(params[:id])
    @programa.cursos.each do |curso|
      curso.destroy
    end
    @programa.destroy

    respond_to do |format|
      format.html { redirect_to programas_url }
      format.json { head :no_content }
    end
  end

  def set_active
    ###### Programas ######
    programa = Programa.find(params[:id])
    programa.update_attributes(:active => params[:active])

    ###### Cursos ######
    programa.cursos.each do |curso|
      curso.update_attributes(:active => params[:active])
      ###### Sesiones ######
      curso.sesions.each do |sesion|
        sesion.update_attributes(:active => params[:active])
      end
    end
    render :nothing => true
  end

  
end

app/helpers/programas_helper.rb
module ProgramasHelper
end

app/views/programas/_delete.html.erb
<div>
  <div class="modal-header">
  	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>Eliminar</h3>
  </div>
	<div class="modal-body">
		<p>Estás a punto de eliminar el programa</p>
		<br />
		<h4 align="center"><%= @programa.nombre %></h4>
		<br />
	</div>
	<div class="modal-footer">
		<%= link_to("Eliminar", @programa, :method => :delete, :class => 'btn btn-inverse') %>
		<a href="#" class="btn" data-dismiss="modal">Cancelar</a>
	</div>
</div>

app/views/programas/_edit.html.erb
<div>
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3>Editar Programa</h3>
	</div>
	<%= simple_form_for(@programa) do |f| %>
	<div class="modal-body">
		<%= f.error_notification %>
		<%= display_base_errors resource %>
		<%= f.input :nombre, :autofocus => true, :label => false, :placeholder => 'Nombre', :class => 'input-block-level' %>
		<p>Tipo:</p>
		<%= f.input :tipo, :collection => ['Social', 'Microempresas'], :label => false, :prompt => "", :class => 'input-block-level' %>
	</div>
	<div class="modal-footer">
		<%= f.button :submit, "Cambiar", :class => 'btn-info' %>
		<% end %>
		<a href="#" class="btn" data-dismiss="modal">Cerrar</a>
	</div>
</div>

app/views/programas/_form.html.erb
<%= simple_form_for(@programa) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre, :autofocus => true, :label => false, :placeholder => 'Nombre', :class => 'input-block-level' %>
  	 <p>Tipo:</p>
  	 <%= f.input :tipo, :collection => ['Social', 'Microempresas'], :label => false, :prompt => "", :class => 'input-block-level' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Enviar", :class => 'btn-info' %>
    <% end %>
    <%= link_to("Atrás", programas_path, :class => 'btn') %>
  </div>

app/views/programas/_new.html.erb
<div>
  <div class="modal-header">
  	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  	<h3>Nuevo Programa</h3>
  </div>
  <%= simple_form_for(@programa) do |f| %>
  <div class="modal-body">
  	 <%= f.error_notification %>
  	 <%= display_base_errors resource %>
  	 <%= f.input :nombre, :autofocus => true, :label => false, :placeholder => 'Nombre', :class => 'input-block-level' %>
  	 <p>Tipo:</p>
  	 <%= f.input :tipo, :collection => ['Social', 'Microempresas'], :label => false, :prompt => "", :class => 'input-block-level' %>
  </div>
  <div class="modal-footer">
  	 <%= f.button :submit, "Crear", :class => 'btn-info' %>
    <% end %>
  	<a href="#" class="btn" data-dismiss="modal">Cerrar</a>
  </div>
</div>

app/views/programas/delete.js.erb
$("#programa-modal").html("<%= escape_javascript(render 'delete') %>")
$("#programa-modal").modal("show")

app/views/programas/edit.html.erb
<div class="span4"></div>
<div class="span4">
	<h1>Error</h1>
	<%= render 'form' %>
</div>

app/views/programas/edit.js.erb
$("#programa-modal").html("<%= escape_javascript(render 'edit') %>")
$("#programa-modal").modal("show")

app/views/programas/index.html.erb
<div class="span3"></div>
<div class="span6">
  <h3>Programas</h3>
  <% if @programas.any? %>
    <table class="table table-condensed table-striped sortable">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Tipo</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @programas.each do |programa| %>
          <tr>
            <td><%= programa.nombre %></td>
            <td><%= programa.tipo %></td>
            <td>
              <div class="btn-group">
                <%= link_to('<i class="icon-search"></i>'.html_safe, programa, :class => 'btn btn-mini') %>
                <%= link_to('<i class="icon-pencil"></i>'.html_safe, edit_programa_path(programa), remote: true, class: "btn btn-mini") %>
                <%= link_to('<i class="icon-trash icon-white"></i>'.html_safe, delete_programa_path(programa), remote: true, class: "btn btn-mini btn-inverse") %>
              </div>
            </td>
            <td>
              <input id="switch-programa-<%=programa.id%>" class="switch-mini switch" type="checkbox" <% if programa.active %> checked <% end %> data-on="info" data-off="danger" data-on-label="Activo" data-off-label="Inactivo">
              <script type="text/javascript">
                $('#switch-programa-<%=programa.id%>').on('switchChange.bootstrapSwitch', function (event, state) {
                  
                  $.ajax({
                    type: "POST",
                    url: "/programas/<%= programa.id %>/set_active",
                    data: {active: state} 
                  });

                });
              </script>
            </td>
            
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <br />
  <% end %>
  <%= link_to "Crear Programa", new_programa_path, remote: true, class: "btn btn-info btn-mini" %>
  <div id="programa-modal" class="modal hide fade modal-small"></div>
</div>


<script type="text/javascript">
  $('.switch').bootstrapSwitch();
</script>

app/views/programas/index_inactivos.html.erb
<div class="span3"></div>
<div class="span6">
  <h3>Programas Inactivos</h3>
  <% if @programas.any? %>
    <table class="table table-condensed table-striped sortable">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Tipo</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @programas.each do |programa| %>
          <tr>
            <td><%= programa.nombre %></td>
            <td><%= programa.tipo %></td>
            <td>
              <div class="btn-group">
                <%= link_to('<i class="icon-search"></i>'.html_safe, programa_inactivo_path(programa), :class => 'btn btn-mini') %>
                <%= link_to('<i class="icon-trash icon-white"></i>'.html_safe, delete_programa_path(programa), remote: true, class: "btn btn-mini btn-inverse") %>
              </div>
            </td>
            <td>
              <input id="switch-programa-<%=programa.id%>" class="switch-mini switch" type="checkbox" <% if programa.active %> checked <% end %> data-on="info" data-off="danger" data-on-label="Activo" data-off-label="Inactivo">
              <script type="text/javascript">
                $('#switch-programa-<%=programa.id%>').on('switch-change', function (e, data) {
                  $.ajax({
                    type: "POST",
                    url: "/programas/<%= programa.id %>/set_active",
                    data: {active: data.value}
                  });

                });
              </script>
            </td>
            
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <br />
  <% end %>
  <div id="programa-modal" class="modal hide fade modal-small"></div>
</div>


<script type="text/javascript">
  $('.switch').bootstrapSwitch();
</script>

app/views/programas/new.html.erb
<div class="span4"></div>
<div class="span4">
	<h1>Error</h1>
	<%= render 'form' %>
</div>

app/views/programas/new.js.erb
$("#programa-modal").html("<%= escape_javascript(render 'new') %>")
$("#programa-modal").modal("show")

app/views/programas/show.html.erb
<div class="span3">
  <ul class="nav nav-tabs nav-stacked sesions-sidenav affix">
    <% if @programas_sociales.any? %>
      <h5>Área Social</h5>
      <% @programas_sociales.each do |programa_social| %>
        <% if programa_social.id == @programa.id %>
          <li class="active">
            <a href="#">
              <i class="icon-chevron-right pull-right"></i>
              <%= programa_social.nombre %>
            </a>
          </li>
        <% else %>
          <li>
            <a href="/programas/<%=programa_social.id%>">
              <i class="icon-chevron-right pull-right"></i>
              <%= programa_social.nombre %>
            </a>
          </li>
        <% end %>
      <% end %>
    <% end %>
    <% if @programas_microempresas.any? %>
      <h5>Área Microempresas</h5>
      <% @programas_microempresas.each do |programas_microempresas| %>
        <% if programas_microempresas.id == @programa.id %>
          <li class="active">
            <a href="#">
              <i class="icon-chevron-right pull-right"></i>
              <%= programas_microempresas.nombre %>
            </a>
          </li>
        <% else %>
          <li>
            <a href="/programas/<%=programas_microempresas.id%>">
              <i class="icon-chevron-right pull-right"></i>
              <%= programas_microempresas.nombre %>
            </a>
          </li>
        <% end %>
      <% end %>
    <% end %>
  </ul>
</div>
<div class="span1"></div>
<div class="span8">
  <%= render 'layouts/messages' %>
  <div class="page-header">
    <h1><%= @programa.nombre %> <small>Área <%= @programa.tipo %></small></h1>
  </div>
	<br />
	<% if @cursos.any? %>
    <table class="table table-condensed table-striped sortable">
      <thead>
        <tr>
          <th>Codigo</th>
          <th>Nombre</th>
          <th>Relator Jefe</th>
          <th>Comuna</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @cursos.each do |curso| %>
          <tr>
            <td><%= curso.codigo %></td>
            <td><%= curso.nombre %></td>
            <td><%= User.find(curso.relator_jefe_id).name %></td>
            <td><%= curso.comuna %></td>
            <td>
                <div class="btn-group">
                  <%= link_to('<i class="icon-search"></i>'.html_safe, curso, :class => 'btn btn-mini') %>
                  <%= link_to('<i class="icon-pencil"></i>'.html_safe, edit_curso_path(curso), remote: true, class: "btn btn-mini") %>
                  <%= link_to('<i class="icon-trash icon-white"></i>'.html_safe, delete_curso_path(curso), remote: true, class: "btn btn-mini btn-inverse") %>
                </div>
              </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "Descargar Excel", programa_path(@programa, format: "xls"), :class => 'btn btn-mini btn-success' %>
  <% else %>
    <h4>No hay cursos en este programa</h4>
    <br />
  <% end %>
  <%= link_to('Agregar Curso', new_curso_path, remote: true, class: "btn btn-mini btn-info") %>
  <div id="curso-modal" class="modal hide fade modal-medium"></div>
</div>

app/views/programas/show_inactivos.html.erb
<div class="span3">
  <ul class="nav nav-tabs nav-stacked sesions-sidenav affix">
    <% if @programas_sociales.any? %>
      <h5>Área Social</h5>
      <% @programas_sociales.each do |programa_social| %>
        <% if programa_social.id == @programa.id %>
          <li class="active">
            <a href="#">
              <i class="icon-chevron-right pull-right"></i>
              <%= programa_social.nombre %>
            </a>
          </li>
        <% else %>
          <li>
            <a href="/programas_inactivos/<%=programa_social.id%>">
              <i class="icon-chevron-right pull-right"></i>
              <%= programa_social.nombre %>
            </a>
          </li>
        <% end %>
      <% end %>
    <% end %>
    <% if @programas_microempresas.any? %>
      <h5>Área Microempresas</h5>
      <% @programas_microempresas.each do |programas_microempresas| %>
        <% if programas_microempresas.id == @programa.id %>
          <li class="active">
            <a href="#">
              <i class="icon-chevron-right pull-right"></i>
              <%= programas_microempresas.nombre %>
            </a>
          </li>
        <% else %>
          <li>
            <a href="/programas_inactivos/<%=programas_microempresas.id%>">
              <i class="icon-chevron-right pull-right"></i>
              <%= programas_microempresas.nombre %>
            </a>
          </li>
        <% end %>
      <% end %>
    <% end %>
  </ul>
</div>
<div class="span1"></div>
<div class="span8">
  <%= render 'layouts/messages' %>
  <div class="page-header">
    <h1><%= @programa.nombre %> <small>Área <%= @programa.tipo %></small></h1>
  </div>
	<br />
	<% if @cursos.any? %>
    <table class="table table-condensed table-striped sortable">
      <thead>
        <tr>
          <th>Codigo</th>
          <th>Nombre</th>
          <th>Comuna</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @cursos.each do |curso| %>
          <tr>
            <td><%= curso.codigo %></td>
            <td><%= curso.nombre %></td>
            <td><%= curso.comuna %></td>
            <td>
                <div class="btn-group">
                  <%= link_to('<i class="icon-search"></i>'.html_safe, curso_inactivo_path(curso), :class => 'btn btn-mini') %>
                  <%= link_to('<i class="icon-trash icon-white"></i>'.html_safe, delete_curso_path(curso), remote: true, class: "btn btn-mini btn-inverse") %>
                </div>
              </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "Descargar Excel", programa_path(@programa, format: "xls"), :class => 'btn btn-mini btn-success' %>
  <% else %>
    <h4>No hay cursos en este programa</h4>
    <br />
  <% end %>
  <div id="curso-modal" class="modal hide fade modal-medium"></div>
</div>