config/routes.rb
SimonDeCirene::Application.routes.draw do
  resources :mensaje_usuarios


  resources :mensajes

  match "/mensajes/:id/delete", to: "mensajes#delete", :as => :delete_mensaje, :via => :get

  match "/not_authorized", to: "home#not_authorized", :as => :not_authorized, :via => :get

  match "/mensajes/new/:id", to: "mensajes#new_with_receiver", :as => :new_mensaje_with_receiver, :via => :get

  resources :formulario_cursos


  resources :formularios do
    collection do
      post :asignar
    end
  end

  match "/formulario/:id/delete", to: "formularios#delete", :as => :delete_formulario, :via => :get
  match "/formulario/:id/asign", to: "formularios#asign", :as => :asign_formulario, :via => :get
  match "/formulario/:id/repeat", to: "formularios#repeat", :as => :repeat_formulario, :via => :get
  match "/formulario/:id/repeat", to: "formularios#repetir", :as => :repetir_formulario, :via => :post
  match "/formulario/resumen", to: "formularios#resumen", :as => :resumen_formularios, :via => :get
  match "/formulario/:id/resumen", to: "formularios#resumen_formulario", :as => :resumen_formulario, :via => :get

  resources :programas

  match "/programas/:id/delete", to: "programas#delete", :as => :delete_programa, :via => :get
  match "/programas/:id/set_active", to: "programas#set_active", :as => :programa_set_active, :via => :post
  match "/programas_inactivos", to: "programas#index_inactivos", :as => :programas_inactivos, :via => :get
  match "/programas_inactivos/:id", to: "programas#show_inactivos", :as => :programa_inactivo, :via => :get


  resources :alumnos do
    collection do
      post :import
      post :search
    end
  end

  match "/cursos/:curso_id/delete_all_alumnos", to: "alumnos#delete_all", :as => :delete_all_alumnos, :via => :get
  match "/cursos/:curso_id/destroy_all_alumnos", to: "alumnos#destroy_all", :as => :destroy_all_alumnos, :via => :get

  match "/cursos/:curso_id/delete_alumno/:id", to: "alumnos#delete", :as => :delete_alumno, :via => :get
  match "/cursos/:id/new_alumno", to: "alumnos#new", :as => :new_alumno, :via => :get
  match "/cursos/:curso_id/edit_alumno/:id", to: "alumnos#edit", :as => :edit_alumno, :via => :get


  resources :sesions

  match "/sesion/:id/delete", to: "sesions#delete", :as => :delete_sesion, :via => :get
  match "/sesion/:id/borrar_asistencia", to: "sesions#borrar_asistencia", :as => :sesion_borrar_asistencia, :via => :post
  match "/cursos/:id/new_sesion", to: "sesions#new", :as => :new_sesion, :via => :get


  resources :cursos, :controller => "cursos"

  match "/cursos/:id/delete", to: "cursos#delete", :as => :delete_curso, :via => :get
  match "/cursos/:id/asistencia", to: "sesions#asistencia", :as => :asistencia_curso, :via => :get
  match "/curso/resumen", to: "cursos#resumen", :as => :resumen_cursos, :via => :get
  match "/cursos_inactivos", to: "cursos#index_inactivos", :as => :cursos_inactivos, :via => :get
  match "/cursos_inactivos/:id", to: "cursos#show_inactivos", :as => :curso_inactivo, :via => :get
  match "/curso_inactivo/resumen", to: "cursos#resumen_inactivos", :as => :resumen_cursos_inactivos, :via => :get

  match "/cursos/:id", to: "cursos#update", :as => :update_curso, :via => :put
  match "/sesions/:id/details", to: "sesions#details", :as => :sesion_details, :via => :get
  match "/alumnos/:id/details", to: "alumnos#details", :as => :alumno_details, :via => :get
  match "/sesions/curso/:id", to: "sesions#curso", :as => :sesion_curso, :via => :get
  match "/alumnos/asistencia/:id", to: "alumnos#asistencia", :via => :post
  match "/download/excel_tipo", to: "alumnos#download_excel"
  match "/curso/:curso_id/formulario/:formulario_id", to: "cursos#formulario", :as => :curso_formulario, :via => :get
  match "/curso/:curso_id/formulario/:formulario_id", to: "cursos#formulario_completado", :via => :post
  match "/ayuda/formularios", to: "home#ayuda_formularios", :as => :ayuda_formulario, :via => :get
  match "/cursos/importar_excel_sence", to: "alumnos#import_sence", :as => :import_excel_sence, :via => :post
  match "/resumen/programa/:id", to: "home#resumen_programa", :as => :resumen_programa, :via => :get
  match "/resumen/curso/:id", to: "home#resumen_curso", :as => :resumen_curso, :via => :get

  authenticated :user do
    root :to => 'home#index'
  end

  match "/user/:id/delete", to: "users#delete", :as => :delete_user, :via => :get

  root :to => "home#index"
  match "/calendario", to: "home#calendario", :as => :calendario, :via => :get

  devise_for :users, :skip => [:registrations]
  devise_scope :user do
  	post "user_registration", 		:to => "users#create"
  	get "edit_user_registration",   :to => "users#edit"
  end
  resources :users, :controller => "users"
  resource :user, only: [:edit] do
    collection do
      put 'update_password'
    end
  end
end

app/models/sesion.rb
class Sesion < ActiveRecord::Base
	audited
	
	belongs_to :curso
	belongs_to :user

 	attr_accessible :comentario, :direccion, :fecha, :hora_inicio, :hora_termino, :tema, :tipo, :curso_id, :user_id, :active

 	validates :tema, :tipo, :direccion, :fecha, :hora_inicio, :hora_termino, :curso_id, :user_id, :presence => true

 	def self.all_active
      return Sesion.where(:active => true).all
    end

    def self.all_active_to_date
      return Sesion.where(:active => true).where('fecha < ?', DateTime.now).all
    end

 	def porcentaje_asistentes
 		alumno_sesiones = AlumnoSesion.where(:sesion_id => self).all
 		asistentes_presentes = 0.0
 		asistentes_totales = 0.0
 		alumno_sesiones.each do |alumno_sesion|
 			if alumno_sesion.presente
 				asistentes_presentes = asistentes_presentes + 1
 			end
 			asistentes_totales = asistentes_totales + 1
 		end

 		if asistentes_totales > 0
	 		porcentaje_asistentes = 0
	 		begin
	 			porcentaje_asistentes = ((asistentes_presentes/asistentes_totales).round(2)*100).to_i
	 		rescue
	 			porcentaje_asistentes = 0
	 		end
	 	else
	 		porcentaje_asistentes = "NA"
	 	end

 		return porcentaje_asistentes
 	end

 	def relator
 		relator = User.find(self.user_id)
 		return relator
 	end
end

app/controllers/sesions_controller.rb
class SesionsController < ApplicationController
  # GET /sesions
  # GET /sesions.json
  def index
    curso_ids = Sesion.where(:user_id => current_user, :active => true).select(:curso_id).group(:curso_id).collect{|p| p.curso_id}
    @cursos = Array.new
    curso_ids.each do |curso_id|
      curso = Curso.find(curso_id)
      @cursos.push curso
    end
    Curso.where(:relator_jefe_id => current_user, :active => true).each do |curso|
      unless @cursos.include?(curso)
        @cursos.push curso
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sesions }
    end
  end

  # GET /sesions/1
  # GET /sesions/1.json
  def show
    @sesion = Sesion.find(params[:id])
    @curso = Curso.find(@sesion.curso_id)

    alumnos_ids = AlumnoCurso.where(:curso_id => @curso.id).select(:alumno_id).group(:alumno_id).collect{|p| p.alumno_id}
    @alumnos = Array.new
    alumnos_ids.each do |alumno_id|
      alumno = Alumno.find(alumno_id)
      @alumnos.push alumno
    end
    @alumnos.sort_by{|alumno| alumno[:apellido_paterno]}

    @sesiones = Sesion.where(:user_id => current_user, :active => true).where(:curso_id => @curso.id).order(:fecha).all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sesion }
    end
  end

  # GET /sesions/new
  # GET /sesions/new.json
  def new
    @sesion = Sesion.new
    @curso_id = params[:id]
  end

  # GET /sesions/1/edit
  def edit
    @sesion = Sesion.find(params[:id])
  end

  # POST /sesions
  # POST /sesions.json
  def create
    @sesion = Sesion.new(params[:sesion])

    respond_to do |format|
      if @sesion.save
        if current_user.has_role? :relator
          format.html { redirect_to sesion_curso_path(@sesion.curso_id) }
        else
          format.html { redirect_to curso_path(@sesion.curso_id) }
        end
        format.json { render json: @sesion, status: :created, location: @sesion }
      else
        format.html { render action: "new" }
        format.json { render json: @sesion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sesions/1
  # PUT /sesions/1.json
  def update
    @sesion = Sesion.find(params[:id])

    respond_to do |format|
      if @sesion.update_attributes(params[:sesion])
        if current_user.has_role? :relator
          format.html { redirect_to sesion_curso_path(@sesion.curso_id) }
        else
          format.html { redirect_to curso_path(@sesion.curso_id) }
        end
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sesion.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @sesion = Sesion.find(params[:id])
  end

  # DELETE /sesions/1
  # DELETE /sesions/1.json
  def destroy
    @sesion = Sesion.find(params[:id])
    @sesion.destroy

    respond_to do |format|
      format.html { redirect_to curso_path(@sesion.curso_id) }
      format.json { head :no_content }
    end
  end

  # GET /sesions/1/details
  # GET /sesions/1/details.json
  def details
    @sesion = Sesion.find(params[:id])

    respond_to do |format|
      format.html # details.html.erb
      format.json { render json: @sesion }
    end
  end

  # GET /sesions/curso/1
  # GET /sesions/curso/1.json
  def curso
    @sesion = Sesion.new
    @alumno = Alumno.new
    @curso = Curso.find(params[:id])
    @formularios = @curso.formularios

    alumnos_ids = AlumnoCurso.where(:curso_id => @curso.id).select(:alumno_id).group(:alumno_id).collect{|p| p.alumno_id}
    @alumnos = @curso.alumnos
    @alumnos.sort_by {|alumno| alumno.apellido_paterno}

    curso_ids = Sesion.where(:user_id => current_user, :active => true).select(:curso_id).group(:curso_id).collect{|p| p.curso_id}
    @cursos = Array.new
    curso_ids.each do |curso_id|
      curso = Curso.find(curso_id)
      @cursos.push curso
    end

    Curso.where(:relator_jefe_id => current_user, :active => true).all.each do |curso|
      unless @cursos.include?(curso)
        @cursos.push curso
      end
    end

    @sesiones = Sesion.where(:curso_id => @curso.id, :active => true).order(:fecha).all

    respond_to do |format|
      format.html # details.html.erb
      format.json { render json: @sesion }
    end
  end

  def asistencia
    @curso = Curso.find(params[:id])
    @alumnos = @curso.alumnos
    @sesiones = @curso.sesions.where(:active => true).order(:fecha)
  end

  def borrar_asistencia
    AlumnoSesion.where(:sesion_id => params[:id]).destroy_all
  end
end

app/helpers/sesions_helper.rb
module SesionsHelper
end

app/views/sesions/_delete.html.erb
<div>
  <div class="modal-header">
  	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h2>Eliminar</h2>
  </div>
	<div class="modal-body">
		<p>Estás a punto de eliminar la sesion</p>
		<br />
		<h4 align="center"><%= @sesion.tema %></h4>
		<br />
	</div>
	<div class="modal-footer">
		<%= link_to("Eliminar", @sesion, :method => :delete, :class => 'btn btn-inverse') %>
		<a href="#" class="btn" data-dismiss="modal">Cancelar</a>
	</div>
</div>

app/views/sesions/_edit.html.erb
<div>
  <div class="modal-header">
  	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h2>Editar Sesión</h2>
  </div>
  <%= simple_form_for(@sesion) do |f| %>
	<div class="modal-body">
		<%= f.error_notification %>
		<%= display_base_errors resource %>
		<%= f.input :tema, :autofocus => true, :label => false, :placeholder => 'Tema', :class => 'input-block-level' %>
		<div class="input-append bootstrap-timepicker">
			<p>De: </p>
      		<input id="sesion_hora_inicio_edit_<%= @sesion.id %>" name="sesion[hora_inicio]" type="text" class="input-small">
      		<span class="add-on"><i class="icon-time"></i></span>
    	</div>
	    <div class="input-append bootstrap-timepicker">
	    	<p>Hasta: </p>
	        <input id="sesion_hora_termino_edit_<%= @sesion.id %>" name="sesion[hora_termino]" type="text" class="input-small">
	        <span class="add-on"><i class="icon-time"></i></span>
	    </div>
		<div class="input-append date">
			<p>Fecha: </p>
			<input type="text" data-behaviour='datepicker' class="string date_picker required" name="sesion[fecha]" id="sesion_fecha" value="<%= @sesion.fecha.strftime("%d/%m/%Y") %>">
			<script type="text/javascript">
				$('[data-behaviour~=datepicker]').datepicker({
				    format: "dd/mm/yyyy",
			        language: "es",
				    autoclose: true
				});
			</script>
		</div>
		<script type="text/javascript">setTimersEdit("#sesion_hora_inicio_edit_<%= @sesion.id %>", "#sesion_hora_termino_edit_<%= @sesion.id %>", "<%= @sesion.hora_inicio.strftime("%I:%M %p") %>", "<%= @sesion.hora_termino.strftime("%I:%M %p") %>");</script>
		<% if current_user.has_role? :relator %>
			<%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
		<% else %>
			<p>Relator: </p>
			<%= f.input :user_id, :collection => (User.with_role :relator).collect{ |p| [p.name, p.id] }, :label => false, :prompt => "", :class => 'input-block-level' %>
		<% end %>
  		<p>Tipo: </p>
  		<%= f.input :tipo, :collection => ['Exposición', 'Trabajo Práctico', 'Invitado', 'Dinámica', 'Otro'], :label => false, :prompt => "", :class => 'input-block-level' %>
      	<%= f.input :direccion, :label => false, :placeholder => 'Direccion', :class => 'input-block-level' %>
  		<%= f.input :comentario, :label => false, :placeholder => 'Comentario', :class => 'input-block-level'  %>
  		<%= f.input :curso_id, :as => :hidden, :input_html => { :value => @sesion.curso_id } %>
	</div>
	<div class="modal-footer">
		<%= f.button :submit, "Cambiar", :class => 'btn-info' %>
		<% end %>
		<a href="#" class="btn" data-dismiss="modal">Cerrar</a>
	</div>
</div>

app/views/sesions/_subir_excel.html.erb
<div id="excel-alumno" class="modal hide fade modal-excel">
  <div class="modal-header">
  	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h2>Subir Excel</h2>
  </div>
	<div class="modal-body">
		<p>Primero debe <strong>elegir el archivo</strong> que desea subir</p>
		<p>Se recomienda seguir el formato del archivo tipo que se puede descargar apretando <strong>"Descargar Excel Tipo"</strong></p>
		<br /><br />
		<%= form_tag import_alumnos_path, multipart: true do %>
    		<%= file_field_tag :file %>
    		<input class="hidden" id="alumno_curso_id" name="curso_id" type="hidden" value="<%= curso.id %>">
    	<br /><br /><br /><br />
    	<p>Una vez elegido el archivo debe apretar <strong>"Importar"</strong></p>
	</div>
	<div class="modal-footer">

			<%= submit_tag "Importar", :class => "btn btn-success" %>
		<% end %>
		<%= link_to "Descargar Excel Tipo", "/download/excel_tipo", :class => "btn btn-info" %>
		<a href="#" class="btn" data-dismiss="modal">Cerrar</a>
	</div>
</div>

app/views/sesions/_subir_excel_sence.html.erb
<div id="excel-sence" class="modal hide fade modal-excel">
  <div class="modal-header">
  	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h2>Subir Excel SENCE</h2>
  </div>
	<div class="modal-body">
		<p>Primero debe <strong>elegir el archivo</strong> que desea subir</p>
		<p>Asegúrese de que el formato del excel es el aceptado por el SENCE</p>
		<br /><br />
		<%= form_tag import_excel_sence_path, multipart: true do %>
    		<%= file_field_tag :file %>
    		<input class="hidden" id="alumno_curso_id" name="curso_id" type="hidden" value="<%= curso.id %>">
    	<br /><br /><br /><br />
    	<p>Una vez elegido el archivo debe apretar <strong>"Importar"</strong></p>
	</div>
	<div class="modal-footer">

			<%= submit_tag "Importar", :class => "btn btn-success" %>
		<% end %>
		<a href="#" class="btn" data-dismiss="modal">Cerrar</a>
	</div>
</div>

app/views/sesions/curso.html.erb
<div class="affix-container">
  <div class="span3">
    <ul class="nav nav-tabs nav-stacked sesions-sidenav affix">
      <% @cursos.each do |curso| %>
        <% if curso.id == @curso.id %>
          <li class="active">
            <a href="#">
              <span class="badge badge-sidenav-active pull-right">
                <%= Sesion.where(:user_id => current_user).where(:curso_id => curso.id).count %>
              </span>
              <%= curso.nombre %>
            </a>
          </li>
        <% else %>
          <li>
            <a href="/sesions/curso/<%=curso.id%>">
              <span class="badge badge-inverse pull-right">
                <%= Sesion.where(:user_id => current_user).where(:curso_id => curso.id).count %>
              </span>
              <%= curso.nombre %>
            </a>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class="span1"></div>
  <div class="span8">
    <%# ------------------------------ Header ------------------------------ %>  
    <div class="page-header">
        <h1><%= @curso.nombre %> <small><%= @curso.codigo %>, <%= @curso.comuna %></small></h1>
    </div>
    <%# ------------------------------ Sesiones ------------------------------ %> 
    <h3>Sesiones</h3>
    <table class="table table-condensed table-striped sortable">
      <thead>
          <tr>
            <th></th>
            <th>Tema</th>
            <th>Horario</th>
            <th>Fecha</th>
            <th>Lugar</th>
            <th></th>
          </tr>
      </thead>
      <tbody>
        <% Sesion.where(:user_id => current_user).where(:curso_id => @curso.id).order(:fecha).each_with_index do |sesion, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= sesion.tema %></td>
            <td><%= sesion.hora_inicio.strftime("%I:%M %p") %> a <%= sesion.hora_termino.strftime("%I:%M %p") %></td>
            <td><%= sesion.fecha.strftime("%d %b, %Y") %></td>
            <td><%= sesion.direccion %></td>
            <td>
              <div class="btn-group">
                <%= link_to '<i class="icon-search"></i>'.html_safe, sesion_path(sesion), :class => 'btn btn-mini' %>
                <%= link_to('<i class="icon-pencil"></i>'.html_safe, edit_sesion_path(sesion), remote: true, class: "btn btn-mini") %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to('Agregar Sesión', new_sesion_path(@curso), remote: true, class: "btn btn-mini btn-info") %>
    <hr>
    <%# ------------------------------ Alumnos ------------------------------ %> 
    <h3>Alumnos</h3>
    <% if @alumnos.any? %>
      <%# ------------------------------ Alumnos Social ------------------------------ %>
      <% if @curso.programa.tipo == "Social" %>
        <table class="table table-condensed table-striped sortable">
          <thead>
              <tr>
                <th></th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Institución</th>
                <th>Cargo</th>
                <th></th>
              </tr>
          </thead>
          <tbody>
            <% @alumnos.each_with_index do |alumno, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= alumno.nombre %></td>
                <td><%= alumno.apellido_paterno %></td>
                <td><%= alumno.nombre_institucion %></td>
                <td><%= alumno.cargo %></td>
                <td>
                  <div class="btn-group">
                    <%= link_to '<i class="icon-search"></i>'.html_safe, alumno_details_path(alumno), :class => 'btn btn-mini' %>
                    <%= link_to('<i class="icon-pencil"></i>'.html_safe, edit_alumno_path(:id => alumno.id, :curso_id => @curso.id), remote: true, class: "btn btn-mini") %>
                    <%= link_to('<i class="icon-trash icon-white"></i>'.html_safe, delete_alumno_path(:id => alumno.id, :curso_id => @curso.id), remote: true, class: "btn btn-mini btn-inverse") %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <%# ------------------------------ Alumnos Microempresas ------------------------------ %>
      <% else %>
        <table class="table table-condensed table-striped sortable">
          <thead>
              <tr>
                <th></th>
                <th>Rut</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Quintil</th>
                <th>Escolaridad</th>
                <th>Rubro</th>
                <th></th>
              </tr>
          </thead>
          <tbody>
            <% @alumnos.each_with_index do |alumno, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= alumno.rut %></td>
                <td><%= alumno.nombre %></td>
                <td><%= alumno.apellido_paterno %></td>
                <td><%= alumno.quintil %></td>
                <td><%= alumno.escolaridad %></td>
                <td>
                  <% rubros = "" %>
                  <% JSON.parse(alumno.profesion).each do |rubro| %>
                    <% if rubro != JSON.parse(alumno.profesion).last %>
                      <% if rubro != "" %>
                        <% rubros = rubros + rubro.to_s + ", " %>
                      <% end %>
                    <% else %>
                      <% if rubro != "" %>
                        <% rubros = rubros + rubro.to_s %>
                      <% end %>
                    <% end %>
                  <% end %>
                  <%= rubros %>
                </td>
                <td>
                  <div class="btn-group">
                    <%= link_to '<i class="icon-search"></i>'.html_safe, alumno_details_path(alumno), :class => 'btn btn-mini' %>
                    <%= link_to('<i class="icon-pencil"></i>'.html_safe, edit_alumno_path(:id => alumno.id, :curso_id => @curso.id), remote: true, class: "btn btn-mini") %>
                    <%= link_to('<i class="icon-trash icon-white"></i>'.html_safe, delete_alumno_path(:id => alumno.id, :curso_id => @curso.id), remote: true, class: "btn btn-mini btn-inverse") %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    <% end %>
    <%= link_to('Agregar Alumno', new_alumno_path(@curso), remote: true, class: "btn btn-mini btn-info") %>
    <a data-toggle="modal" href="#excel-alumno" class="btn btn-mini btn-success" type="button">Subir Excel</a>
    <%= link_to "Asistencia", asistencia_curso_path(@curso), :class => 'btn btn-mini' %>

    <%= render :partial => 'subir_excel', :locals => {:curso => @curso} %>

    <%# ------------------------------ Formularios ------------------------------ %> 
      <hr>
      <h3>Formularios</h3>
      <% if @formularios.any? %>
        <table class="table table-condensed table-striped sortable">
          <thead>
              <tr>
                <th>Cógido</th>
                <th>Nombre</th>
                <th>Estado</th>
              </tr>
          </thead>
          <tbody>
            <% @formularios.each do |formulario| %>
              <tr>
                <td><%= formulario.codigo %></td>
                <td><%= link_to formulario.nombre, formulario.url %></td>
                <td>
                  <div class="btn-group" data-toggle="buttons-radio">
                    <button type="button" id="contestado-<%= formulario.id %>" class="btn btn-mini btn-info">Contestado</button>
                    <button type="button" id="no-contestado-<%= formulario.id %>" class="btn btn-mini btn-info">Pendiente</button>
                  </div>
                </td>
                <% if formulario.contestado?(@curso) %>
                  <script type="text/javascript">
                    $("#contestado-<%= formulario.id %>").button('toggle');
                    $("#contestado-<%= formulario.id %>").removeClass("btn-info");
                    $("#contestado-<%= formulario.id %>").addClass("btn-success");
                  </script>
                <% else %>
                  <script type="text/javascript">
                    $("#no-contestado-<%= formulario.id %>").button('toggle');
                    $("#no-contestado-<%= formulario.id %>").removeClass("btn-info");
                    $("#no-contestado-<%= formulario.id %>").addClass("btn-danger");
                  </script>
                <% end %>
                <script type="text/javascript">
                  $("#contestado-<%= formulario.id %>").click(function() {
                    $.ajax({
                      type: "POST",
                      url: "/curso/<%= @curso.id %>/formulario/<%= formulario.id %>",
                      data: {estado: 'Contestado'}
                    });
                    $("#no-contestado-<%= formulario.id %>").removeClass("btn-danger");
                    $("#no-contestado-<%= formulario.id %>").addClass("btn-info");
                    $(this).removeClass("btn-info");
                    $(this).addClass("btn-success");
                  });
                  $("#no-contestado-<%= formulario.id %>").click(function() {
                    $.ajax({
                      type: "POST",
                      url: "/curso/<%= @curso.id %>/formulario/<%= formulario.id %>",
                      data: {estado: 'Pendiente'}
                    });
                    $("#contestado-<%= formulario.id %>").removeClass("btn-success");
                    $("#contestado-<%= formulario.id %>").addClass("btn-info");
                    $(this).removeClass("btn-info");
                    $(this).addClass("btn-danger");
                  });
                </script>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>

      <p>El curso todavía no tiene formularios</p>
   
      <% end %>

    <br /><br /><br />
    <div id="sesion-modal" class="modal hide fade modal-medium"></div>
    <div id="alumno-modal" class="modal hide fade modal-medium"></div>
  </div>
</div>

app/views/sesions/details.html.erb
<div class="span3"></div>
<div class="span6">
  <div class="hero-unit">
    <h1><%= @sesion.tema %></h1>
    <br /><br />

    <p>
      El relator de esta sesión es <b><%= User.find(@sesion.user_id).name %></b>
    </p>

    <p>
      Se impartirá de <b><%= @sesion.hora_inicio.strftime("%I:%M %p") %></b> a <b><%= @sesion.hora_termino.strftime("%I:%M %p") %></b>
    </p>

    <p>
      El día <b><%= @sesion.fecha.strftime("%B %d, %Y") %></b>
    </p>

    <p>
      Es una sesión del tipo <b><%= @sesion.tipo %></b>
      
    </p>

    <p>
      Se llevará a cabo en <b><%= @sesion.direccion %></b>
    </p>

    <p>
      <%= @sesion.comentario %>
    </p>

    <br />
    <%= link_to('Editar', edit_sesion_path(@sesion), remote: true, class: "btn btn-large btn-info") %>
    <% if current_user.has_role? :relator %>
      <%= link_to 'Atrás', sesion_path(@sesion), :class => 'btn btn-large' %>
    <% else %>
      <%= link_to 'Atrás', curso_path(@sesion.curso_id), :class => 'btn btn-large' %>
    <% end %>
    <a data-toggle="modal" href="#delete-sesion-<%= @sesion.id %>" class="btn btn-large btn-inverse" type="button">Eliminar</a>
  </div>
  <div id="sesion-modal" class="modal hide fade modal-medium"></div>
</div>