config/routes.rb
SimonDeCirene::Application.routes.draw do
  resources :mensaje_usuarios


  resources :mensajes

  match "/mensajes/:id/delete", to: "mensajes#delete", :as => :delete_mensaje, :via => :get

  match "/not_authorized", to: "home#not_authorized", :as => :not_authorized, :via => :get

  match "/mensajes/new/:id", to: "mensajes#new_with_receiver", :as => :new_mensaje_with_receiver, :via => :get

  resources :formulario_cursos


  resources :formularios do
    collection do
      post :asignar
    end
  end

  match "/formulario/:id/delete", to: "formularios#delete", :as => :delete_formulario, :via => :get
  match "/formulario/:id/asign", to: "formularios#asign", :as => :asign_formulario, :via => :get
  match "/formulario/:id/repeat", to: "formularios#repeat", :as => :repeat_formulario, :via => :get
  match "/formulario/:id/repeat", to: "formularios#repetir", :as => :repetir_formulario, :via => :post
  match "/formulario/resumen", to: "formularios#resumen", :as => :resumen_formularios, :via => :get
  match "/formulario/:id/resumen", to: "formularios#resumen_formulario", :as => :resumen_formulario, :via => :get

  resources :programas

  match "/programas/:id/delete", to: "programas#delete", :as => :delete_programa, :via => :get
  match "/programas/:id/set_active", to: "programas#set_active", :as => :programa_set_active, :via => :post
  match "/programas_inactivos", to: "programas#index_inactivos", :as => :programas_inactivos, :via => :get
  match "/programas_inactivos/:id", to: "programas#show_inactivos", :as => :programa_inactivo, :via => :get


  resources :alumnos do
    collection do
      post :import
      post :search
    end
  end

  match "/cursos/:curso_id/delete_all_alumnos", to: "alumnos#delete_all", :as => :delete_all_alumnos, :via => :get
  match "/cursos/:curso_id/destroy_all_alumnos", to: "alumnos#destroy_all", :as => :destroy_all_alumnos, :via => :get

  match "/cursos/:curso_id/delete_alumno/:id", to: "alumnos#delete", :as => :delete_alumno, :via => :get
  match "/cursos/:id/new_alumno", to: "alumnos#new", :as => :new_alumno, :via => :get
  match "/cursos/:curso_id/edit_alumno/:id", to: "alumnos#edit", :as => :edit_alumno, :via => :get


  resources :sesions

  match "/sesion/:id/delete", to: "sesions#delete", :as => :delete_sesion, :via => :get
  match "/sesion/:id/borrar_asistencia", to: "sesions#borrar_asistencia", :as => :sesion_borrar_asistencia, :via => :post
  match "/cursos/:id/new_sesion", to: "sesions#new", :as => :new_sesion, :via => :get


  resources :cursos, :controller => "cursos"

  match "/cursos/:id/delete", to: "cursos#delete", :as => :delete_curso, :via => :get
  match "/cursos/:id/asistencia", to: "sesions#asistencia", :as => :asistencia_curso, :via => :get
  match "/curso/resumen", to: "cursos#resumen", :as => :resumen_cursos, :via => :get
  match "/cursos_inactivos", to: "cursos#index_inactivos", :as => :cursos_inactivos, :via => :get
  match "/cursos_inactivos/:id", to: "cursos#show_inactivos", :as => :curso_inactivo, :via => :get
  match "/curso_inactivo/resumen", to: "cursos#resumen_inactivos", :as => :resumen_cursos_inactivos, :via => :get

  match "/cursos/:id", to: "cursos#update", :as => :update_curso, :via => :put
  match "/sesions/:id/details", to: "sesions#details", :as => :sesion_details, :via => :get
  match "/alumnos/:id/details", to: "alumnos#details", :as => :alumno_details, :via => :get
  match "/sesions/curso/:id", to: "sesions#curso", :as => :sesion_curso, :via => :get
  match "/alumnos/asistencia/:id", to: "alumnos#asistencia", :via => :post
  match "/download/excel_tipo", to: "alumnos#download_excel"
  match "/curso/:curso_id/formulario/:formulario_id", to: "cursos#formulario", :as => :curso_formulario, :via => :get
  match "/curso/:curso_id/formulario/:formulario_id", to: "cursos#formulario_completado", :via => :post
  match "/ayuda/formularios", to: "home#ayuda_formularios", :as => :ayuda_formulario, :via => :get
  match "/cursos/importar_excel_sence", to: "alumnos#import_sence", :as => :import_excel_sence, :via => :post
  match "/resumen/programa/:id", to: "home#resumen_programa", :as => :resumen_programa, :via => :get
  match "/resumen/curso/:id", to: "home#resumen_curso", :as => :resumen_curso, :via => :get

  authenticated :user do
    root :to => 'home#index'
  end

  match "/user/:id/delete", to: "users#delete", :as => :delete_user, :via => :get

  root :to => "home#index"
  match "/calendario", to: "home#calendario", :as => :calendario, :via => :get

  devise_for :users, :skip => [:registrations]
  devise_scope :user do
  	post "user_registration", 		:to => "users#create"
  	get "edit_user_registration",   :to => "users#edit"
  end
  resources :users, :controller => "users"
  resource :user, only: [:edit] do
    collection do
      put 'update_password'
    end
  end
end

app/models/mensaje.rb
class Mensaje < ActiveRecord::Base
	attr_accessible :caracter, :cuerpo, :titulo
	validates :cuerpo, :titulo, :presence => true

	def receptores_ids
		receptores = Array.new
		receptores_ids = MensajeUsuario.where(:mensaje_id => self).select(:usuario_id).group(:usuario_id).collect{|p| p.usuario_id}
		receptores_ids.each do |receptor_id|
			receptores.push receptor_id.to_s
		end
		return receptores
	end

	def receptores_string
		receptores = ""
		receptores_ids = MensajeUsuario.where(:mensaje_id => self).select(:usuario_id).group(:usuario_id).collect{|p| p.usuario_id}
		receptores_ids.each do |receptor_id|
			receptores += User.find(receptor_id).name + ", "
		end
		return receptores[0..(receptores.length - 3)]
	end

	def eliminar_receptores
		receptores_ids = MensajeUsuario.where(:mensaje_id => self).select(:usuario_id).group(:usuario_id).collect{|p| p.usuario_id}
		receptores_ids.each do |receptor_id|
			MensajeUsuario.where(:mensaje_id => self, :usuario_id => receptor_id).destroy_all
		end
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/controllers/mensajes_controller.rb
class MensajesController < ApplicationController
  # GET /mensajes
  # GET /mensajes.json
  def index
    @mensajes = Mensaje.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mensajes }
    end
  end

  # GET /mensajes/1
  # GET /mensajes/1.json
  def show
    @mensaje = Mensaje.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mensaje }
    end
  end

  # GET /mensajes/new
  # GET /mensajes/new.json
  def new
    @mensaje = Mensaje.new
  end

  def new_with_receiver
    @mensaje = Mensaje.new
    @user = User.find(params[:id])
  end

  # GET /mensajes/1/edit
  def edit
    @mensaje = Mensaje.find(params[:id])
  end

  # POST /mensajes
  # POST /mensajes.json
  def create
    @mensaje = Mensaje.new(:titulo => params[:mensaje][:titulo], :cuerpo => params[:mensaje][:cuerpo], :caracter => params[:mensaje][:caracter])

    respond_to do |format|
      if @mensaje.save
        params[:user_ids].each do |user_id|
          MensajeUsuario.create(:usuario_id => user_id, :mensaje_id => @mensaje.id)
        end
        puts URI(request.referer).path
        if URI(request.referer).path == '/mensajes'
          format.html { redirect_to mensajes_path }
        else
          user = User.find(params[:user_ids][0])
          format.html { redirect_to resumen_formularios_path, notice: 'El mensaje ha sido enviado a ' + user.name }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @mensaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mensajes/1
  # PUT /mensajes/1.json
  def update
    @mensaje = Mensaje.find(params[:id])

    respond_to do |format|
      if @mensaje.update_attributes(:titulo => params[:mensaje][:titulo], :cuerpo => params[:mensaje][:cuerpo], :caracter => params[:mensaje][:caracter])
        @mensaje.eliminar_receptores
        if params[:user_ids] != nil && params[:user_ids].kind_of?(Array)
          params[:user_ids].each do |user_id|
            MensajeUsuario.create(:usuario_id => user_id, :mensaje_id => @mensaje.id)
          end
        end
        format.html { redirect_to mensajes_path }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mensaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mensajes/1
  # DELETE /mensajes/1.json
  def destroy
    @mensaje = Mensaje.find(params[:id])
    @mensaje.destroy

    receptores_ids = MensajeUsuario.where(:mensaje_id => params[:id]).select(:usuario_id).group(:usuario_id).collect{|p| p.usuario_id}
    receptores_ids.each do |receptor_id|
      MensajeUsuario.where(:usuario_id => receptor_id, :mensaje_id => params[:id]).destroy_all
    end

    respond_to do |format|
      format.html { redirect_to mensajes_url }
      format.json { head :no_content }
    end
  end

  def delete
    @mensaje = Mensaje.find(params[:id])
  end
end

app/helpers/mensajes_helper.rb
module MensajesHelper
end

app/views/mensajes/_delete.html.erb
<div>
  <div class="modal-header">
  	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h2>Eliminar</h2>
  </div>
	<div class="modal-body">
		<p>Se eliminará el mensaje a todos los destinatarios</p>
		<br />
		<h4 align="center"><%= @mensaje.titulo %></h4>
		<br />
	</div>
	<div class="modal-footer">
		<%= link_to("Eliminar", @mensaje, :method => :delete, :class => 'btn btn-inverse') %>
		<a href="#" class="btn" data-dismiss="modal">Cancelar</a>
	</div>
</div>

app/views/mensajes/_edit.html.erb
<div>
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 class="text-center">Editar Mensaje</h3>
	</div>
	<%= simple_form_for @mensaje, :url => mensaje_path(@mensaje), :html => {:method => :put } do |f| %>
	<div class="modal-body">
		<%= f.error_notification %>
		<%= display_base_errors resource %>
		<%= f.input :titulo, :autofocus => true, :label => false, :placeholder => "Título", :input_html => { :class => "input-block-level" } %>
		<%= f.input :cuerpo, :label => false, :placeholder => 'Mensaje', :as => "Text", :input_html => { :rows => 10, :class => "input-block-level" } %>
		<%= f.input :caracter, :collection => ['Positivo', 'Neutro', 'Negativo'], :label => false, :prompt => "Carácter del mensaje", :input_html => { :class => "input-block-level" } %>
		<%= select_tag 'user_ids[]', options_for_select((User.with_role :relator).map {|c| [c.name, c.id]}), :multiple => true, :class => "input-block-level", :id => "select-relatores" %>
	</div>
	<div class="modal-footer">
		<%= f.button :submit, "Cambiar", :class => 'btn-info' %>
		<% end %>
		<a href="#" class="btn" data-dismiss="modal">Cerrar</a>
	</div>
</div>

<script type="text/javascript">
  $("#select-relatores").val(<%= raw @mensaje.receptores_ids %>).select2({
    placeholder: "Selecciona uno o varios usuarios"
  });
</script>

app/views/mensajes/_form.html.erb
<%= simple_form_for(@mensaje) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :titulo, :autofocus => true, :label => false, :placeholder => "Título", :input_html => { :class => "input-block-level" } %>
	<%= f.input :cuerpo, :label => false, :placeholder => 'Mensaje', :as => "Text", :input_html => { :rows => 10, :class => "input-block-level" } %>
	<%= f.input :caracter, :collection => ['Positivo', 'Neutro', 'Negativo'], :label => false, :prompt => "Carácter del mensaje", :input_html => { :class => "input-block-level" } %>
	<%= select_tag 'user_ids[]', options_for_select((User.with_role :relator).map {|c| [c.name, c.id]}), :multiple => true, :class => "input-block-level", :id => "select-relatores" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Enviar", :class => 'btn-info' %>
    <% end %>
    <%= link_to("Atrás", mensajes_path, :class => 'btn') %>
  </div>

<script type="text/javascript">
  $("#select-relatores").select2({
    placeholder: "Selecciona uno o varios usuarios"
  });
</script>

app/views/mensajes/_new.html.erb
<div>
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 class="text-center">Nuevo Mensaje</h3>
	</div>
	<%= simple_form_for(@mensaje) do |f| %>
	<div class="modal-body">
		<%= f.error_notification %>
		<%= display_base_errors resource %>
		<%= f.input :titulo, :autofocus => true, :label => false, :placeholder => "Título", :input_html => { :class => "input-block-level" } %>
		<%= f.input :cuerpo, :label => false, :placeholder => 'Mensaje', :as => "Text", :input_html => { :rows => 10, :class => "input-block-level" } %>
		<%= f.input :caracter, :collection => ['Positivo', 'Neutro', 'Negativo'], :label => false, :prompt => "Carácter del mensaje", :input_html => { :class => "input-block-level" } %>
		<%= select_tag 'user_ids[]', options_for_select((User.with_role :relator).map {|c| [c.name, c.id]}), :multiple => true, :class => "input-block-level", :id => "select-relatores" %>
		<label class="checkbox inline">
			<input class="btn" value="Input" type="checkbox" id="checkbox" >Seleccionar Todos
		</label>
	</div>
	<div class="modal-footer">
		<%= f.button :submit, "Crear", :class => 'btn-info' %>
		<% end %>
		<a href="#" class="btn" data-dismiss="modal">Cerrar</a>
	</div>
</div>

<script type="text/javascript">
	$("#select-relatores").select2({
		placeholder: "Selecciona uno o varios usuarios"
	});
	$("#checkbox").click(function(){
		if($("#checkbox").is(':checked') ){
			$("#select-relatores > option").prop("selected","selected");
			$("#select-relatores").trigger("change");
		}
		else{
			$("#select-relatores > option").removeAttr("selected");
			$("#select-relatores").trigger("change");
		}
	});
</script>

app/views/mensajes/_new_with_receiver.html.erb
<div>
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 class="text-center">Nuevo Mensaje</h3>
	</div>
	<%= simple_form_for(@mensaje) do |f| %>
	<div class="modal-body">
		<%= f.error_notification %>
		<%= display_base_errors resource %>
		<%= f.input :titulo, :autofocus => true, :label => false, :placeholder => "Título", :input_html => { :class => "input-block-level" } %>
		<%= f.input :cuerpo, :label => false, :placeholder => 'Mensaje', :as => "Text", :input_html => { :rows => 10, :class => "input-block-level" } %>
		<%= f.input :caracter, :collection => ['Positivo', 'Neutro', 'Negativo'], :label => false, :prompt => "Carácter del mensaje", :input_html => { :class => "input-block-level" } %>
		<%= hidden_field_tag 'user_ids[]', @user.id %>
	</div>
	<div class="modal-footer">
		<%= f.button :submit, "Crear", :class => 'btn-info' %>
		<% end %>
		<a href="#" class="btn" data-dismiss="modal">Cerrar</a>
	</div>
</div>

app/views/mensajes/delete.js.erb
$("#mensaje-modal").html("<%= escape_javascript(render :partial => 'delete') %>")
$("#mensaje-modal").modal("show")

app/views/mensajes/edit.html.erb
<div class="span4"></div>
<div class="span4">
	<h1>Error</h1>
	<%= render 'form' %>
</div>

app/views/mensajes/edit.js.erb
$("#mensaje-modal").html("<%= escape_javascript(render :partial => 'edit') %>")
$("#mensaje-modal").modal("show")

app/views/mensajes/index.html.erb
<div class="span2"></div>
<div class="span8">
  <h3>Mensajes</h3>
  <% if @mensajes.any? %>
    <table class="table table-condensed table-striped sortable">
      <thead>
        <tr>
          <th>Mensaje</th>
          <th>Receptores</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @mensajes.each do |mensaje| %>
          <tr>
            <td>
              <span data-content="<%= mensaje.cuerpo %>" rel="popover" data-placement="bottom" data-original-title="<%=mensaje.titulo%>" data-html="true" class="sesion-popover"><%= mensaje.titulo %></span>
            </td>
            <td><%= mensaje.receptores_string %></td>
            <td>
              <div class="btn-group">
                <%= link_to('<i class="icon-pencil"></i>'.html_safe, edit_mensaje_path(mensaje), remote: true, :class => 'btn btn-mini') %>
                <%= link_to('<i class="icon-trash icon-white"></i>'.html_safe, delete_mensaje_path(mensaje), remote: true, class: "btn btn-mini btn-inverse") %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <br />
  <% end %>
  <%= link_to("Nuevo Mensaje", new_mensaje_path, remote: true, :class => 'btn btn-mini btn-info') %>
  <div id="mensaje-modal" class="modal hide fade modal-mensaje"></div>
</div>

app/views/mensajes/new.html.erb
<div class="span4"></div>
<div class="span4">
	<h1>Error</h1>
	<%= render 'form' %>
</div>

app/views/mensajes/new.js.erb
$("#mensaje-modal").html("<%= escape_javascript(render :partial => 'new') %>")
$("#mensaje-modal").modal("show")

app/views/mensajes/new_with_receiver.js.erb
$("#mensaje-modal").html("<%= escape_javascript(render :partial => 'new_with_receiver') %>")
$("#mensaje-modal").modal("show")

app/views/mensajes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @mensaje.titulo %>
</p>

<p>
  <b>Cuerpo:</b>
  <%= @mensaje.cuerpo %>
</p>

<p>
  <b>Caracter:</b>
  <%= @mensaje.caracter %>
</p>


<%= link_to 'Edit', edit_mensaje_path(@mensaje) %> |
<%= link_to 'Back', mensajes_path %>